<?php
	include("../../class/file/myfile.php");
	include("../../class/file/myimage.php");
	include("../../class/file/imageresource.php");
	include("../../class/file/fileresource.php");
	include("../../class/clock/clockroot.php");
	include("../../class/clock/clock.php");
	include("../../class/clocktag/clocktagroot.php");
	include("../../class/clocktag/clocktag.php");
	include("../../class/tag/tagroot.php");
	include("../../class/tag/tag.php");
?>